<?php
declare(strict_types=1);

// Sotaproject SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

SotaprojectUtility::setRegistrar(function (SotaprojectUtility $u): void {
    $u->clean = [SotaprojectClean::class, 'call'];
    $u->done = [SotaprojectDone::class, 'call'];
    $u->make_error = [SotaprojectMakeError::class, 'call'];
    $u->feature_add = [SotaprojectFeatureAdd::class, 'call'];
    $u->feature_hook = [SotaprojectFeatureHook::class, 'call'];
    $u->feature_init = [SotaprojectFeatureInit::class, 'call'];
    $u->fetcher = [SotaprojectFetcher::class, 'call'];
    $u->make_fetch_def = [SotaprojectMakeFetchDef::class, 'call'];
    $u->make_context = [SotaprojectMakeContext::class, 'call'];
    $u->make_options = [SotaprojectMakeOptions::class, 'call'];
    $u->make_request = [SotaprojectMakeRequest::class, 'call'];
    $u->make_response = [SotaprojectMakeResponse::class, 'call'];
    $u->make_result = [SotaprojectMakeResult::class, 'call'];
    $u->make_point = [SotaprojectMakePoint::class, 'call'];
    $u->make_spec = [SotaprojectMakeSpec::class, 'call'];
    $u->make_url = [SotaprojectMakeUrl::class, 'call'];
    $u->param = [SotaprojectParam::class, 'call'];
    $u->prepare_auth = [SotaprojectPrepareAuth::class, 'call'];
    $u->prepare_body = [SotaprojectPrepareBody::class, 'call'];
    $u->prepare_headers = [SotaprojectPrepareHeaders::class, 'call'];
    $u->prepare_method = [SotaprojectPrepareMethod::class, 'call'];
    $u->prepare_params = [SotaprojectPrepareParams::class, 'call'];
    $u->prepare_path = [SotaprojectPreparePath::class, 'call'];
    $u->prepare_query = [SotaprojectPrepareQuery::class, 'call'];
    $u->graphql_body = [SotaprojectGraphql::class, 'body'];
    $u->graphql_errors = [SotaprojectGraphql::class, 'errors'];
    $u->result_basic = [SotaprojectResultBasic::class, 'call'];
    $u->result_body = [SotaprojectResultBody::class, 'call'];
    $u->result_headers = [SotaprojectResultHeaders::class, 'call'];
    $u->transform_request = [SotaprojectTransformRequest::class, 'call'];
    $u->transform_response = [SotaprojectTransformResponse::class, 'call'];
});
